---
- name: Test SSH connectivity
  hosts: all
  gather_facts: no
  tasks:
    - name: Ping target host
      ping:
        
    - name: Get hostname
      command: hostname
      register: host_name
      
    - name: Display hostname
      debug:
        msg: "Successfully connected to {{ host_name.stdout }}"
