---
- name: Get IP address information
  hosts: all  # Adjust to target specific hosts or groups in your inventory
  gather_facts: no  # Skip gathering facts for faster execution
  tasks:
    - name: Run `ip a` command
      command: ip a
      register: ip_output  # Register the output to display later

    - name: Show IP address information
      debug:
        var: ip_output.stdout  # Display the command output
