---
- name: Gather Current Time and System Information
  hosts: all
  gather_facts: true
  tasks:
    - name: Get current time
      command: date '+%Y-%m-%d %H:%M:%S'
      register: current_time

    - name: Get system uptime
      command: uptime -p
      register: system_uptime

    - name: Get system timezone
      command: timedatectl show --property=Timezone --value
      register: system_timezone

    - name: Display results
      debug:
        msg:
          - "Current Time: {{ current_time.stdout }}"
          - "System Uptime: {{ system_uptime.stdout }}"
          - "Timezone: {{ system_timezone.stdout }}"
